/**
 * WINDOWS 95 APP CENTER - MYTESTAPP
 * Auto-generated by create-app.js
 */

import { Kernel } from '../core/Kernel.js';
import type { IWindowsApp } from '../core/Types.js';

class MyTestApp implements IWindowsApp {
    public windowId: string = 'win-my-test-app';

    constructor(params: Record<string, any> = {}) {
        this.init();
    }

    private init(): void {
        console.log('[MyTestApp] Application initialized');
        // Your logic here
    }

    public terminate(): void {
        console.log('[MyTestApp] Application terminated');
        // Cleanup logic here
    }
}

// Register with Kernel
Kernel.registerApp('my-test-app', MyTestApp, {
    name: 'MyTestApp',
    icon: '📦',
    description: 'Auto-generated application'
});

export { MyTestApp };
