import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const appName = process.argv[2];

if (!appName) {
    console.error('❌ Please provide an App Name (e.g. npm run generate:app myApp)');
    process.exit(1);
}

// Convert "my-app" or "myApp" to PascalCase "MyApp" for Class Name
const className = appName
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

const appId = appName.toLowerCase().replace(/[^a-z0-9]/g, '-');
const filePath = path.join(__dirname, '../js/apps', `${className}.ts`);

if (fs.existsSync(filePath)) {
    console.error(`❌ App ${className} already exists at ${filePath}`);
    process.exit(1);
}

const template = `/**
 * WINDOWS 95 APP CENTER - ${className.toUpperCase()}
 * Auto-generated by create-app.js
 */

import { Kernel } from '../core/Kernel.js';
import { IWindowsApp } from '../core/Types.js';

class ${className} implements IWindowsApp {
    public windowId: string = 'win-${appId}';

    constructor(params: Record<string, any> = {}) {
        this.init();
    }

    private init(): void {
        console.log('[${className}] Application initialized');
        // Your logic here
    }

    public terminate(): void {
        console.log('[${className}] Application terminated');
        // Cleanup logic here
    }
}

// Register with Kernel
Kernel.registerApp('${appId}', ${className}, {
    name: '${className}',
    icon: '📦',
    description: 'Auto-generated application'
});

export { ${className} };
`;

fs.writeFileSync(filePath, template, 'utf8');

console.log(`✅ Successfully created app ${className} at:`);
console.log(`   ${filePath}`);
console.log(`\n💡 Vite will automatically detect and load this app in main.ts!`);
